### PR TITLE
use relURL

### LINKED ISSUE #23: Something breaks the page for the previews
There is something making the branch preview sites render oddly.
Images missing, menu items not being selectable, pages dissapearing. 

Dont know what is happening, but would love input.

Example:
branch: https://github.com/rladies/website/pull/22
renders: https://deploy-preview-22--pensive-babbage-969fad.netlify.app/directory/

Dont ever merge this branch, it is nonsensical.

### PR DESCRIPTION
**Pull request by maelle**
Fix #23 

The reason for this is that the preview URL created by Netlify doesn't end with a slash so in the preview index the logo URL is https://deploy-preview-22--pensive-babbage-969fad.netlify.appimages/logo.png

### CODE REVIEW

**Comment by maelle** [comment]
I think I learnt this from Alison Hill https://twitter.com/ma_salmon/status/1276583886546513922

**Comment by maelle** [comment]
I'll look for all occurrences

**Comment by maelle** [comment]
@Athanasiamo there's a failure for getting the directory but if you look at the last commit with a non-failed build, there are less missing images and the menu seems to work?

**Comment by maelle** [comment]
https://deploy-preview-24--pensive-babbage-969fad.netlify.app/

**Comment by maelle** [comment]
@Athanasiamo I think it's all good now? Please tell me if any weird things you had noticed still happens in this preview.

**Comment by Athanasiamo** [comment]
aye, this seems to be ok!

**Pull request merged**
